// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvF8xfFQ6rSOLHJR-CK0tye1VhwNTOxyM',
    appId: '1:863279156824:web:d5c90c1b0a3d6cbb33c42d',
    messagingSenderId: '863279156824',
    projectId: 'busmet-845b1',
    authDomain: 'busmet-845b1.firebaseapp.com',
    storageBucket: 'busmet-845b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZYu0JOvdteJADXsrTsi2d39IgD5gKiOs',
    appId: '1:863279156824:android:0d017dfc522b533633c42d',
    messagingSenderId: '863279156824',
    projectId: 'busmet-845b1',
    storageBucket: 'busmet-845b1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvF8xfFQ6rSOLHJR-CK0tye1VhwNTOxyM',
    appId: '1:863279156824:web:c84a88568332e05933c42d',
    messagingSenderId: '863279156824',
    projectId: 'busmet-845b1',
    authDomain: 'busmet-845b1.firebaseapp.com',
    storageBucket: 'busmet-845b1.firebasestorage.app',
  );
}
